# Generated by Django 4.1.4 on 2023-01-06 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона в формате 7XXXXXXXXXX (X - цифра от 0 до 9)', regex='^7\\d{10}$')], verbose_name='Номер телефона клиента')),
                ('code', models.CharField(max_length=3, verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(max_length=200, verbose_name='Тег')),
                ('timezone', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Дата и время запуска рассылки')),
                ('time_end', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('text', models.TextField(verbose_name='Текст сообщения для доставки клиенту')),
                ('filter_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Фильтр: код мобильного оператора')),
                ('filter_tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фильтр: тег')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Отправка')),
                ('status', models.JSONField(blank=True, null=True, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='notify.client', verbose_name='Клиент')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='notify.distribution', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
